Enemy
przybyla/Omega pull request #6
Opened 2024-02-06 12:44 UTC by Sal3k

Added enemyAI
Enemy is moving towards player when player step in the DetectionArea, then he will follow the player until player is out of ChaseArea. Works neatly :D

Additionally i've added ROAM state to create an enemy that can move around. Collisions seems to work fine.

2024-02-06 20:47 UTC, tallyon commented
dodałes wroga na jakąś scenę? Bo widzę enemy.tscn ale nie ma tam gracza wrzuconego a nie ma też żadnych zmian na scenie level_1.tscn, jak odpalam grę to nie widzę nigdzie wroga

2024-02-06 20:49 UTC, tallyon commented on Scripts/Enemy.gd
> +@onready var anim: AnimatedSprite2D = $AnimatedSprite2D
zamiast tego myślę, że fajnie by było jakbyś zrobił `@export var anim: AnimatedSprite2D` i przeciągnął referencję w edytorze

2024-02-06 20:53 UTC, tallyon commented
w sumie super by było jakbyś spróbował z tego wroga zrobić maszynę stanów, która ma 3 stany:
- idle: wiadomo, stoi w miejscu, odtwarza animację idle, można nawet dorobić że co jakiś czas idzie w losowe miejsce niedaleko
- chase: wchodzi w ten stan jak gracz wejdzie w strefę aggro, goni gracza aż będzie na tyle blisko, że będzie kolizja
- attack: wchodzi w ten stan jak ma kolizję z graczem, będzie co X sekund odpalał funkcję ataku (która teraz może printować "enemy 1 hits the player!")
- return: wchodzi w ten stan jak gracz wyjdzie ze strefy deaggro, będzie szedł do miejsca gdzie się zespawnił żeby tam wejść w idle

Tutaj jest tutorial jak zrobić state machine w godot: https://docs.godotengine.org/en/3.2/tutorials/misc/state_design_pattern.html#

2024-02-11 14:58 UTC, tallyon requested changes

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/IdleState.gd
> +		Transitioned.emit(self, "ChaseState")
idealnie byłoby nie używać stringów do zmiany stanu

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/IdleState.gd
> +	if direction.length() > 10 && direction.length() < 75:
wartości `10` i `75` powinny być stałymi albo exportowanymi zmiennymi jak `wanter_time_min`

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/IdleState.gd
> +	player = get_tree().get_first_node_in_group("Player")
to dobrze byłoby zamienić na jakąś (statyczną?) metodę `func find_player() -> CharacterBody2D`

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/IdleState.gd
> +	var should_move = randi_range(0, 4) as bool
wartość `4` zamienić na exportowaną zmienną float w zakresie [0.0;1.0] opisującą procentową szansę na to, że wylosujemy stanie w miejscu zamiast chodzenia

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/GengarEnemy.gd
> +	if velocity.length() == 0:
`else` zamiast kolejnego `if`

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/AttackState.gd
> +		Transitioned.emit(self, "IdleState")
`25` i `75` powinny być zmiennymi. Widziałem je już w wskrypcie `IdleState`, więc pewnie najlepiej byłoby je przesunąć do skryptu enemy i niech oba stany sobie je pobierają z niego

2024-02-11 14:58 UTC, tallyon commented on Enemies/Gengar/AttackState.gd
> +@export var enemy: CharacterBody2D
może dałoby się tą referencję umieść w `StateMachine` i niech state'y sobie pobierają/dostają przy wejściu?

2024-02-11 16:14 UTC, tallyon approved these changes

2024-02-11 16:15 UTC, tallyon commented on Enemies/Gengar/ChaseState.gd
> +	if direction.length() > 25:
@Sal3k z tą wartością nie wiem co zrobić bo nie jestem pewien co ona oznacza w sumie. Zobacz sobie w tym samym skrypcie poniżej jak użyłem parametrów z `@export` na innych stanach jak na przykład `if direction.length() > chase_range_max:` i spróbuj zadeklarować tą wartość `25` jako zmienną na jakimś stanie i użyj tej zmiennej tutaj żebyśmy nie mieli takich losowych wartości liczbowych w kodzie

2024-02-11 16:15 UTC, tallyon commented on Enemies/Gengar/AttackState.gd
> +	if direction.length() > 25:
@Sal3k tutaj też jest to `25`

2024-02-11 18:11 UTC, Sal3k commented on Enemies/Gengar/AttackState.gd
> +	if direction.length() > 25:
Jeśli odległosc jest wieksza od 25 to przechodzimy z Attack na Chase state. Wiec cos w stylu attack_range maybe

2024-02-11 18:36 UTC, merged